services:
  mongo:
    image: mongo:latest
    container_name: mongo-advanced-authentication-system
    restart: always
    environment:
      MONGO_INITDB_DATABASE: advanced-authentication-system
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ab12
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
